name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - develop 

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1.0.4
        with:
          target-repo: osscar-org/widget-periodictable   
          service-name: gh 
          target-state: develop 
          debug: true 
