name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '13.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install jupyterlab==2.2.8
        python -m pip install ipywidgets
    - name: Build the extension
      run: |
        jlpm && jlpm run build
        jupyter labextension install .
        python -m jupyterlab.browser_check
    - name: Check PyPi and NPM version
      run: python version_check.py
